### ISSUE TITLE
Clean the API

### ISSUE THREAD

**Issue by Dargish** [Dargish/GLRender#15]
Try to remove as many library dependencies from the API. This might include passing around raw pointer handlers instead of boost shared pointers and only using the shared pointers internally.

Definitely keep things like tinyxml and json internal to their appropriate libs.

This is quite a large future ticket and will probably be broken down into a full or most of a milestone at some point.

**Comment by Dargish** [comment]
Going to rework the separate libraries of the engine into one library with a clean API using just the std library in its interface. Dependencies such as boost and sfml will be kept private.

**Comment by Dargish** [comment]
- [ ] #22 Move Core library into combined library
- [ ] #23 Move EntityComponentSystem library into combined library
- [ ] #24 Move Serialisation library into combined library
- [ ] #25 Move IO library into combined library
- [ ] #26 Move Graphics library into combined library
- [ ] #27 Move Component library into combined library
- [ ] #28 Move System library into combined library
- [ ] #29 Update Tests to use new combined library
- [ ] #30 Update GLRender test game to use new combined library
